name: Сообщить о баге
description: Расскажите о баге в приложении
title: "[БАГ]: "
labels: ["баг"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🚨 Перед заполнением убедитесь, что:
        - ✅ Вы скачали последнюю версию приложения из релизов или телеграм-канала
        - ✅ Вы посмотрели открытые Issues и не нашли ничего похожего

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Проверка перед отправкой"
      options:
        - label: "Я скачал последнюю версию приложения"
          required: true
        - label: "Я проверил открытые Issues и не нашел похожих"
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "Описание проблемы"
      description: "Ясно и четко опишите, в чем состоит баг"
      placeholder: "Например: Приложение вылетает при нажатии на кнопку сохранения"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Как воспроизвести"
      description: "Шаги для воспроизведения бага"
      placeholder: |
        1. Зайти в '...'
        2. Нажать на '....'
        3. Пролистать до '....'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Ожидаемое поведение"
      description: "Что вы ожидали увидеть вместо бага"
      placeholder: "Например: Кнопка сохранения должна сохранять данные без вылета приложения"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Скриншоты/Видео"
      description: "Прикрепите скриншоты или ссылки на видео, демонстрирующие проблему"
      placeholder: "Загрузите скриншоты в комментарий или вставьте ссылки на изображения"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "Операционная система"
      description: "На какой ОС происходит баг"
      options:
        - Android
        - iOS
        - Windows
        - MacOS
        - Linux
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: "Модель устройства"
      description: "Модель вашего устройства"
      placeholder: "Например: POCO X3 PRO, iPhone 13, Samsung S21"
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: "Версия приложения"
      description: "Версия приложения, в которой обнаружен баг"
      placeholder: "Например: 1.3.5, 2.0.0"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: "Дополнительная информация"
      description: "Любые другие замечания, логи ошибок или контекст"
      placeholder: "Например: Ошибка происходит только при отсутствии интернета, или приложите логи ошибок"
    validations:
      required: false
